import {
  Controller,
  Get,
  Query,
  UseGuards,
  Req,
  Res,
  BadRequestException,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiBearerAuth,
  ApiQuery,
} from '@nestjs/swagger';
import { Request, Response } from 'express';
import * as ExcelJS from 'exceljs';
import { JwtGuard } from '../identity/guards/jwt.guard';
import { RolesGuard } from '../../shared/guards/roles.guard';
import { Roles } from '../../shared/decorators/roles.decorator';
import { VatReturnService } from './vat-return.service';

function fmtDate(d: Date): string {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

@ApiTags('VAT Return')
@Controller('v1/vat-return')
export class VatReturnController {
  constructor(private readonly vatReturnService: VatReturnService) {}

  private getCtx(req: Request): any {
    return (req as any)._billinxContext;
  }

  private parseDates(startDate: string, endDate: string): [Date, Date] {
    if (!startDate || !endDate) {
      throw new BadRequestException('startDate and endDate are required');
    }
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      throw new BadRequestException('Invalid date format — use YYYY-MM-DD');
    }
    return [start, end];
  }

  @Get('summary')
  @UseGuards(JwtGuard, RolesGuard)
  @Roles('OWNER', 'ADMIN', 'ACCOUNTANT', 'VIEWER')
  @ApiBearerAuth()
  @ApiOperation({
    summary: 'Get VAT return summary and schedule previews for a filing period',
  })
  @ApiQuery({ name: 'startDate', required: true, example: '2026-01-01' })
  @ApiQuery({ name: 'endDate', required: true, example: '2026-03-31' })
  async getSummary(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Req() req: Request,
  ) {
    const [start, end] = this.parseDates(startDate, endDate);
    const ctx = this.getCtx(req);
    return this.vatReturnService.getVatReturnData(ctx.tenantId, start, end);
  }

  @Get('export')
  @UseGuards(JwtGuard, RolesGuard)
  @Roles('OWNER', 'ADMIN', 'ACCOUNTANT')
  @ApiBearerAuth()
  @ApiOperation({
    summary: 'Download pre-filled VAT 002 Excel file for a filing period',
  })
  @ApiQuery({ name: 'startDate', required: true, example: '2026-01-01' })
  @ApiQuery({ name: 'endDate', required: true, example: '2026-03-31' })
  async exportExcel(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Req() req: Request,
    @Res() res: Response,
  ) {
    const [start, end] = this.parseDates(startDate, endDate);
    const ctx = this.getCtx(req);
    const data = await this.vatReturnService.getVatReturnData(
      ctx.tenantId,
      start,
      end,
    );

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Billinx';
    workbook.created = new Date();

    // 1. Explanatory Notes
    const s1 = workbook.addWorksheet('Explanatory Notes');
    s1.getCell('A1').value =
      'Generated by Billinx. Complete Schedules D, E, and F manually before submitting.';

    // 2. VAT RETURNS FORM (blank — NRS auto-populates from schedules)
    workbook.addWorksheet('VAT RETURNS FORM');

    // 3. A - Sales
    const sA = workbook.addWorksheet('A - Sales');
    sA.addRow([
      'Name of Customer',
      'TAX ID of Customer',
      'PRODUCT NAME',
      'PRODUCT CATEGORY (0=VATable 1=Exempt 2=Zero-Rated)',
      'PRODUCT DESCRIPTION',
      'PLACE OF CONSUMPTION/Sale (State Code)',
      'PLACE OF CONSUMPTION/Sale (Local Government Code)',
      'Sales/Income Exclusive of VAT',
    ]);
    for (const row of data.scheduleA) {
      sA.addRow([
        row.customerName,
        row.customerTin,
        row.productName,
        row.productCategory,
        row.productDescription,
        row.stateCode,
        row.lgaCode,
        row.amountExclVat,
      ]);
    }

    // 4. A1A2 - Exempt Zero (blank)
    workbook.addWorksheet('A1A2 - Exempt Zero');

    // 5. B - Sales Adjustments
    const sB = workbook.addWorksheet('B - Sales Adjustments');
    sB.addRow([
      'DESCRIPTION',
      'CUSTOMER TAXID',
      'NAME OF CUSTOMER',
      'DATE OF TRANSACTION',
      'TAX INVOICE NUMBER',
      'INVOICE AMOUNT',
      'ADJUSTED SALES AVAILABLE FOR CLAIM',
    ]);
    for (const row of data.scheduleB) {
      sB.addRow([
        row.description,
        row.customerTin,
        row.customerName,
        fmtDate(new Date(row.transactionDate)),
        row.invoiceNumber,
        row.invoiceAmount,
        row.adjustedAmount,
      ]);
    }

    // 6. C - Purchases (blank — auto-populates from C2)
    workbook.addWorksheet('C - Purchases');

    // 7. C_2_Purchases List
    const sC2 = workbook.addWorksheet('C_2_Purchases List');
    sC2.addRow([
      'SELLER NAME',
      'SELLER TAX ID',
      'PRODUCT DESCRIPTION/NAME (CATEGORY)',
      'Purchases Amount Exclusive of VAT',
      'VAT_STATUS',
    ]);
    for (const row of data.scheduleC2) {
      sC2.addRow([
        row.sellerName,
        row.sellerTin,
        row.productDescription,
        row.amountExclVat,
        row.vatStatus,
      ]);
    }

    // 8. D - Imports
    const sD = workbook.addWorksheet('D - Imports');
    sD.getCell('A1').value =
      'Complete manually — Billinx does not capture import data.';

    // 9. E - Self-Charge VAT
    const sE = workbook.addWorksheet('E - Self-Charge VAT');
    sE.getCell('A1').value = 'Complete manually if applicable.';

    // 10. F - Sales to MDAs
    const sF = workbook.addWorksheet('F - Sales to MDAs');
    sF.getCell('A1').value = 'Complete manually if applicable.';

    const yyyy = start.getFullYear();
    const mm = String(start.getMonth() + 1).padStart(2, '0');
    const filename = `VAT_002_${yyyy}_${mm}.xlsx`;

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    await workbook.xlsx.write(res);
  }
}
